### ISSUE TITLE
RuntimeWarning: divide by zero encountered in double_scalars

### ISSUE THREAD

**Issue by tkreyche** [mihtjel/nanovna-saver#107]
Console window showed this warning message on startup, but only the first time I ran the program. Does not show the message subsequently. Running on a Windows 10 64 bit computer.

Version nanovna-saver-v0.2.0.

See https://github.com/mihtjel/nanovna-saver for further details
Settings: C:/Users/tkrey/AppData/Roaming/NanoVNASaver/NanoVNASaver.ini
C:\Users\tkrey\AppData\Local\Temp\_MEI51882\NanoVNASaver\Chart.py:3572: RuntimeWarning: divide by zero encountered in double_scalars

**Comment by mihtjel** [comment]
Thanks, I'll take a look at it!

**Comment by mihtjel** [comment]
Should be fixed in the latest version.
