### ISSUE TITLE
0.2.2 Crash after loading calibration file

### ISSUE THREAD

**Issue by acug01** [mihtjel/nanovna-saver#132]
**Describe the bug**

**To Reproduce**
1. Perform a calibration in NVSaver.
2. Save calibration file.
3. Exit and restart NVSaver.
4. Load calibration file.
5. Set Continuous Sweep.
6. Start sweep.
7. NVSaver crashes.

**Desktop (please complete the following information):**
 - OS: Windows 7 SP1
 - NanoVNA-Saver version: 0.2.2

**Additional context**
Windows Crash report:
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	nanovna-saver-v0.2.2.exe
  Application Version:	0.0.0.0
  Application Timestamp:	5d24a31b
  Fault Module Name:	ucrtbase.DLL
  Fault Module Version:	10.0.10137.0
  Fault Module Timestamp:	556ebf74
  Exception Code:	40000015
  Exception Offset:	000764fa
  OS Version:	6.1.7601.2.1.0.768.3
  Locale ID:	1033
  Additional Information 1:	ff52
  Additional Information 2:	ff52df55cf70ef1ee9a6fa8528cd88a6
  Additional Information 3:	f26d
  Additional Information 4:	f26d3b73534facc55216d73a307ca16d

Calibration File:
[S21.cal.txt](https://github.com/mihtjel/nanovna-saver/files/4051328/S21.cal.txt)

~agc

**Comment by MintoWitteveen** [comment]
Can confirm this. Here however the application just exits, without any waring or message...

**Comment by mihtjel** [comment]
There is a 0.2.2-1 .exe in the 0.2.2 release now, which should fix it.

**Comment by MintoWitteveen** [comment]
Hi mihtjel thanks that fixed it for me!

**Comment by rmalsbury50** [comment]
I am running 0.2.2 and have crash when hitting the save option. Running Win10

**Comment by mihtjel** [comment]
Looks like this issue is fixed in 0.2.2-1.
