### ISSUE TITLE
Discontinuities(spikes) in measurements when > 1 segments sweep

### ISSUE THREAD

**Issue by MintoWitteveen** [mihtjel/nanovna-saver#136]
**Describe the bug**
When I do a sweep with more than 1 segment there are often (large) spikes in the graphs, suggesting some sort of discontinuity / wrong measurements on the boundaries of the segments.
These are not completely reproduceable (i.e. not the same every scan). But they are absent when scanning one (1) segment EXCEPT sometimes there is a spike at the beginning or the end of the scan. See attached screenshots.
These spikes also appear when I do a calibration with more than one segment (as one does of course)

**To Reproduce**
1. Go to 'sweep control'
2. Click on 'segments and put in a value other than 1 (say 10 for optimal effect)'
3. Click on Sweep
4. See effect. Attached two screenshot, one with 1 segment and one with 10 segments

**Expected behavior**
No spikes on segment boundaries :-)

**Screenshots**
Done.

**Desktop (please complete the following information):**
 - OS: W10
 - Python version: [if applicable]
 - NanoVNA-Saver version:  0.2.2

![1 segment sweep](https://user-images.githubusercontent.com/59967221/72536060-da20c380-3879-11ea-8251-5b438b72a74c.png)
![10 segment sweep](https://user-images.githubusercontent.com/59967221/72536078-e1e06800-3879-11ea-8602-7da95c29b049.png)

**Comment by mihtjel** [comment]
What firmware version are you running? This looks a lot like a bug that used to be present in some old firmwares.

**Comment by MintoWitteveen** [comment]
I am running v0.2.3-2  18 oct 2019.
Just got the nanoVNA, will check for newer firmware.

**Comment by MintoWitteveen** [comment]
Hi that was it!
I upgraded from the 2019.10.18 firmware to the latest 2019.11.25 and now the spikes are gone!

Thanks for the quick response!

**Comment by mihtjel** [comment]
Sounds good! Glad it's working for you, and I hope you enjoy the software.
