### ISSUE TITLE
NanoVNASaver 0.0.9 - save the last calibrated file in the Calibration file name

### ISSUE THREAD

**Issue by RolandWa** [mihtjel/nanovna-saver#14]
Hi mihtjel,

Please save the last calibrated file in the Calibration file name, or build a drop down list with the saved calibration.

Best Regards
Roland

**Comment by mihtjel** [comment]
Thanks for the suggestion, it seems like a sensible thing to do.

**Comment by mihtjel** [comment]
Implemented in 0.0.10
