### ISSUE TITLE
S-Parameter file (Touchstone v1.1) with format "DB" are not displayed correctly

### ISSUE THREAD

**Issue by bvernoux** [mihtjel/nanovna-saver#141]
**Describe the bug**
When we import S-Parameter file (Touchstone v1.1) with format "DB" (dB-angle) it is not displayed correctly.
Note:  S-Parameter file / Touchstone v1.1 with format "RI" (Real-imaginary) & "MA" (Magnitude-angle) work fine.

**To Reproduce**
1. Open [NanoVNA Saver 0.2.2-1](https://github.com/mihtjel/nanovna-saver/releases/tag/v0.2.2)
2. Click on 'Files ...'
3. Click on 'Load as sweep' or 'Load as reference' (issue is the same)
4. See **Screenshot/Files** with working file (attenuator-0643_RI_Hz_OK.s2p) and non working file (attenuator-0643_DB_Hz_KO.s2p) 
Those files contains exactly same data in 2 different format (RI & DB).

**Expected behavior**
The S-Parameter (Touchstone v1.1) file format "DB" shall be displayed correctly like for other format  "RI" & "MA"  

**Screenshot/Files**
In this example I have loaded following files:
* attenuator-0643_RI_Hz_OK.s2p (in brown) as sweep which is OK
* attenuator-0643_DB_Hz_KO.s2p (in blue) as reference which is KO as it shall be identical to sweep/attenuator-0643_RI_Hz_OK.s2p
![image](https://user-images.githubusercontent.com/432709/73091955-de815800-3edb-11ea-8686-35b3f8b5f19f.png)

See file archive to reproduce the issue: [attenuator-0643_DB_Hz_KO_attenuator-0643_RI_Hz_OK.zip](https://github.com/mihtjel/nanovna-saver/files/4109906/attenuator-0643_DB_Hz_KO_attenuator-0643_RI_Hz_OK.zip)

**Desktop:**
 - OS: Windows7 Pro 64bits
 - Python version: N/A (Use the one embedded in nanovna-saver-v0.2.2-1.exe)
 - NanoVNA-Saver version: nanovna-saver-v0.2.2-1.exe

**Comment by bvernoux** [comment]
This issue should be fixed by https://github.com/mihtjel/nanovna-saver/pull/140 to be confirmed

**Comment by mihtjel** [comment]
I am not sure how the pull request would be related to this? But I will take a look at your examples! :-)

**Comment by bvernoux** [comment]
If you want more files for test I can provide more and I can also provide my tool which convert SnP to any format RI, DB, MA (so far I have not released it on github)

**Comment by zarath** [comment]
@bvernoux thanks for finding the bug ans supplying that test data.

Can you supply the same data as ma to me, so that i can use it as test data for comparision?

Sorry, that I wasn't able to look earlier on this issue

**Comment by bvernoux** [comment]
See same data in MA format 
[attenuator-0643_MA_Hz_OK.zip](https://github.com/mihtjel/nanovna-saver/files/4114242/attenuator-0643_MA_Hz_OK.zip)

**Comment by mihtjel** [comment]
Thanks for fixing this, @zarath :-)

**Comment by bvernoux** [comment]
Very nice job and fast fix thanks
I confirm all work fine now
