### ISSUE TITLE
Assist novice users with clarifying save-as S1P and S2P file types

### ISSUE THREAD

**Issue by zstadler** [mihtjel/nanovna-saver#148]
**Is your feature request related to a problem? Please describe.**

For a novice user, it is not clear what is the difference between saving an S1P file and saving an S2P file.

<img height="221px" src="https://user-images.githubusercontent.com/1304610/73640917-cba71a00-4677-11ea-8965-460ce4967b3e.png" />

Moreover, after choosing a file type, the save as dialog shows both file types. 

<img width="75%" src="https://user-images.githubusercontent.com/1304610/73642996-62290a80-467b-11ea-9157-8407dc4c2a49.png"/>

It does not mean I can write an S2P file after choosing "Save File (S1P)", right!?

**Describe the solution you'd like**

1. Change the text on the save buttons to say "1-Port" and "2-Port"

   <img height="221px" src="https://user-images.githubusercontent.com/1304610/73640346-bbdb0600-4676-11ea-944d-04967b7d129b.png" />

2. Use the above selected file suffix in the save-as dialog.
   For example, after choosing "Save 1-Port file (S1P)":

   <img width="75%" src="https://user-images.githubusercontent.com/1304610/73640732-7c60e980-4677-11ea-9a17-17c809eb645c.png"/>

**Pull Request**

Will be sent soon.

**Comment by zarath** [comment]
Merged in Development branch
