### ISSUE TITLE
Impedance S11 /Z/ on markers

### ISSUE THREAD

**Issue by UlrichD61** [mihtjel/nanovna-saver#150]
Hello,
I'm using Saver primarily to measure impedances on components.
Quite simple to measure and display Real/Imag, and it's great that features be added day by day !!
That's the reason I'm writing:   It would be ideal to see the value of  S11 /Z/ in the markers as well.

In the charts  S11 /Z/ can be selected to display the **graph** of S11 /Z/.
It would be great to also include S11 /Z/ to the selectable entries in "Marker Settings" for showing the S11 /Z/ as a Ohm-number for each markers frequency.

Would be of great help and avoids using Pytharoras for each and every marker.
Thanks !

![S11-Z  ](https://user-images.githubusercontent.com/56156578/73887999-11790380-486d-11ea-848f-9210b46606d7.JPG)

**Comment by yo2naa** [comment]
It would be a nice addition, please add |Z| to the markers. I've recently measured some CMM chokes and use markers for each band of interest, it would be great to directly read the |Z| on each marker.
Thank you.

**Comment by zarath** [comment]
I'll take a look

**Comment by zarath** [comment]
Merged in development branch
