### ISSUE TITLE
Translate nanovna-saver

### ISSUE THREAD

**Issue by stefkpl** [mihtjel/nanovna-saver#168]
Hi,
I would like append translation files.

Like this :
```
/languages/FR_fr.py
/languages/IT_it.py
etc ...
```

Is it possible? 

Regards

Stef.

**Comment by mihtjel** [comment]
Hi Stef,
the software isn't currently setup to accept translations. The texts for buttons, labels etc. are embedded within the code.

I have been quite limited in the time I have been able to dedicate to NanoVNA-Saver recently, and I prefer to focus this time on functionality over, for example, translations. Should the feature be implemented in the future, I will get back to you!

Thanks,
Rune

**Comment by zarath** [comment]
Duplicate of #139
