### ISSUE TITLE
Manual/Auto setting vertical scale on S11 and S21 Log/Lin graphs

### ISSUE THREAD

**Issue by anthropic-radio-source** [mihtjel/nanovna-saver#22]
It is great what you have done so far but could you make it possible to set the vertical scale limits on the S11 and S21 Log/Lin graphs so that they can be set automatically (as it is now) or manually. 

When set manually, it allows easier comparison between similar antenna or filter measurements.

**Comment by mihtjel** [comment]
It's been on my list of "things I want at some point", and now there's an issue for it as well :-)

**Comment by anthropic-radio-source** [comment]
Sorry, not an issue, more of a feature request to your already great software!

**Comment by anthropic-radio-source** [comment]
Great, Incorporated in version 0.0.12.
