### ISSUE TITLE
Not detected by USB/COM port

### ISSUE THREAD

**Issue by saintofinternet** [mihtjel/nanovna-saver#25]
**Describe the bug**
The nanovna device is not being deteceted by the USB as a COM port device.

It is not responding at all on the PC 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Psynosaur** [comment]
Hi there

Can you connect to the NanoVNA via a serial COM at all?

when connected via your favourite serail application type info.

```
info
Kernel:       4.0.0
Compiler:     GCC 4.9.3 20150529 (release) [ARM/embedded-4_9-branch revision 227977]
Architecture: ARMv6-M
Core Variant: Cortex-M0
Port Info:    Preemption through NMI
Platform:     STM32F072xB Entry Level Medium Density devices
Board:        NanoVNA
Build time:   Sep  9 2019 - 21:45:20
ch>
```

Please let us know

**Comment by mihtjel** [comment]
No response.
