### ISSUE TITLE
Add color for secondary reference

### ISSUE THREAD

**Issue by gaionim** [mihtjel/nanovna-saver#30]
In RealImaginaryChart   R and X share same color.
If "show lines" is enabled,  reference lines are using same color as sweep lines; it is a Bug or a feature ? 
73

**Comment by mihtjel** [comment]
There's a bug regarding the reference lines; and adding a secondary colour is being considered, but not yet prioritized :-)

**Comment by gaionim** [comment]
thanks,
version 0.1.2 add reference color, but still bug for line.
I'll open new bug.
