### ISSUE TITLE
RealImaginary charts wrong color for primary line 

### ISSUE THREAD

**Issue by gaionim** [mihtjel/nanovna-saver#39]
Primary line color is same as secondary, see attach

73
![Istantanea_2019-10-11_19-58-15](https://user-images.githubusercontent.com/14140143/66673914-f05b2a00-ec61-11e9-9686-a62cd9303a32.png)

**Comment by mihtjel** [comment]
Oh dear, I thought I'd managed to fix it, but obviously not! I'll go over it again.
