### ISSUE TITLE
Precise movement between points

### ISSUE THREAD

**Issue by SMinin** [mihtjel/nanovna-saver#47]
**Is your feature request related to a problem? Please describe.**

Lack of precise movement between points. Sometimes you need to look at information about neighboring points, and getting into them with the mouse is sometimes difficult.

**Describe the solution you'd like**
For example, using the keyboard cursor.

**Describe alternatives you've considered**

**Additional context**

**Comment by mihtjel** [comment]
It's a good point. I think I might make up/down arrow in the marker frequency input fields move to the next/previous point. Would that fit?

**Comment by PY3IG** [comment]
Additional Suggestion
A floating window next to the mouse indicating some information would aid selection.
Thanks!!

**Comment by SMinin** [comment]
mihtjel, up-down or left-right arrows (it seems to me more intuitively) would be a great solution.
