### ISSUE TITLE
Nannovnasaver makes nanovna usable above 900MHz.

### ISSUE THREAD

**Issue by PA3CCE** [mihtjel/nanovna-saver#72]
Hello,
I flashed my NanoVNA wiyh software that supports frequecies up to 1500 MHz.
Normally using it above 900 MHz it's hardly usable because of all the noise.
By using NanoVNASaver and it's possibilitty to set many averagings and/or segments
and accepting the long sweep time, I achieved well usable results.
Fantastic program this is.
Jos

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Hello,

**Describe alternatives you've considered**

**Additional context**

**Comment by mihtjel** [comment]
Thank you very much :-)
