### ISSUE TITLE
NanoVNA Harmonics band boundaries peaks v0.15

### ISSUE THREAD

**Issue by MaxCrt** [mihtjel/nanovna-saver#76]
Due to harmonic usage at frequencies greater than 250 MHz, the band boundaries (e.g. 300 MHz) have large peaks.
My suggest is to interpolate near boundaries to suppress those peaks

Thank you

BR,
Max IK1RGI

**Comment by mihtjel** [comment]
Hello Max,
generally, there are two ways to solve this: On-device calibration, or in-app calibration. I suggest that you carefully calibrate your NanoVNA across the entire frequency span you intend to use, and then *also* run a calibration within NanoVNA-Saver using the calibration assistant, and using more than the default 101 points by changing the "segments" setting - for example, 10 segments = 1010 points. This usually solves the issue for me.

You may need to reduce the threshold frequency, using for example the NanoVNA-Q firmware, if you keep having problems at the transition frequency.
