### ISSUE TITLE
VSWRAnalysis show same value

### ISSUE THREAD

**Issue by gaionim** [mihtjel/nanovna-saver#78]
VSWRAnalysis with more than 3 values shows 3 time the lowest

I expect you to show the lowest 3

![Istantanea_2019-11-06_09-28-27](https://user-images.githubusercontent.com/14140143/68281645-68a5e700-0078-11ea-934c-e1dbe7c3743d.png)

If needed I can attach samples data

**Comment by mihtjel** [comment]
This certainly looks like a bug!

For testing, I'd appreciate the data file, it would make things easier :-)

**Comment by gaionim** [comment]
[sample.zip](https://github.com/mihtjel/nanovna-saver/files/3813521/sample.zip)

**Comment by gaionim** [comment]
there is mismatch from index on dips and minimums  when you delete min value.
if you change the value so it is non more the minimum  seems to work

< dips.remove(np.min(dips))
> dips[np.argmin(dips)] = 1000
