### ISSUE TITLE
Proxy Authentication

### ISSUE THREAD

**Issue by dl8aap** [mihtjel/nanovna-saver#81]
By starting the software with update option activated, results in an error 407 Proxy Authentication Required. Only if PC is behind a firewall/proxy LAN structure.

**Comment by mihtjel** [comment]
Sounds like something that only happens if you're in an environment with a proxy that requires authentication. Does the application crash, or does it just give you the error?

**Comment by dl8aap** [comment]
Yep, you're right with the environment. The application doesn't crash, it just makes this error. And it happens only when the application starts.
