### ISSUE TITLE
Unable to sweep using Lenovo Win10 Tablet

### ISSUE THREAD

**Issue by mydevpeeps** [mihtjel/nanovna-saver#84]
**Describe the bug**
Error when trying to use on windows 10 tablet when using v0.1.5. Works on v0.1.2.

**To Reproduce**
i can do connect to nano, and it connects, and sets the freq i put in the software, and then tries to sweep it and then i get this error: "Failed reading data 0 20 times. Data outside expected valid ranges, or in an unexpected format."

**Expected behavior**
Initial sweep displays.

**Screenshots**
N/A

**Version(s) Tested:**
v0.1.2: successful
v0.1.3: successful
v0.1.4: fails
v0.1.5: fails

**Desktop (works):**
 - OS: Windows 10 Pro b1903
 - Python version: NA
 - NanoVNA-Saver version: 0.1.5

**Tablet (doesnt work)**
 - Model: Lenovo K3011W (Atom Z2760)
 - OS: Windows 10 Home v1511 (10.0.10586)
 - Python version: NA
 - NanoVNA-Saver version: 0.1.5

**Additional context**
N/A

**Comment by mydevpeeps** [comment]
I'm sorry that somehow submitted. I am re-writing it.

**Comment by mihtjel** [comment]
Hi,
sorry for taking so long to get back to you - I didn't get notified that you had edited the comments!

The error message you received is usually because the NanoVNA itself is not calibrated. Before using your NanoVNA with NanoVNA-Saver, make sure it is fully calibrated, all 5 steps, and that the calibration is saved. I personally keep a calibration of the full frequency span (50k - 1500M) in the Cal 0 save slot, which is loaded by default, and which allows me to use NanoVNA-Saver with no issues.

If the device is not calibrated, the returned values from it may be so far from the expected range that the software rejects them as transmission errors.

Good luck with your NanoVNA!

**Comment by mydevpeeps** [comment]
I did full calibration using the software from my desktop a few weeks ago. Right now its set to the max range of 50K-900M) by default and boots up that way until i do a recall for another slot. I did the calibration on slot 0 and saved the full range. Then, I changed the ranges for the other slots, but all in the software and while still calibrated, and saved them on the nano.  

Do you suggest I attempt to re-calibrate it on the desktop (where it does work) and then try it again on the tablet (where it doesn't)?

Note: It's somewhat ironic that i cant use the software to calibrate it because as soon as I plug it in.. it does a sweep automatically, fails, and then disconnects the vna. I'm not sure if that is forced (because the vna is always sweeping when you turn it on) or by software design - but I'd prefer it not sweep once and stop when connected.

**Comment by mihtjel** [comment]
Hi,
you can't do an on-device calibration using NanoVNA-Saver. It only does in-application calibration thus far - so any calibration on the device itself has to be done on the device, not via the PC.

I do find it interesting that it doesn't work on one computer, but does on another. I could possibly use some more information: If you start NanoVNA-Saver from a command prompt, and use the "-d" command line option, it shows you debugging info. This will also show what values it is reading when the read fails - that could be useful for figuring out what's wrong.

If you use "-D filename.txt", it saves a log file of these readings (here to "filename.txt")

**Comment by mydevpeeps** [comment]
I ran the debug from the desktop and the tablet so you have a comparison. It's the same VNA, same usb cable, same .exe in both instances. 

Interestingly it seems to work on version 0.1.2, but not on 0.1.5. If you want me to try versions 0.1.3 and 0.1.4 send me direct download links so we can figure out which version had a breaking change.

[desktop-v0.1.5.txt](https://github.com/mihtjel/nanovna-saver/files/3831655/desktop-v0.1.5.txt)
[tablet-v0.1.5.txt](https://github.com/mihtjel/nanovna-saver/files/3831656/tablet-v0.1.5.txt)
[tablet-v0.1.2.txt](https://github.com/mihtjel/nanovna-saver/files/3831657/tablet-v0.1.2.txt)
[desktop-v0.1.2.txt](https://github.com/mihtjel/nanovna-saver/files/3831658/desktop-v0.1.2.txt)

**Comment by mydevpeeps** [comment]
OK. I did some more testing. Here are the results, along with two more files.

**Version(s) Tested:**
v0.1.2: successful
v0.1.3: successful
v0.1.4: fails
v0.1.5: fails

[tablet-0.1.4.txt](https://github.com/mihtjel/nanovna-saver/files/3831760/tablet-0.1.4.txt)
[tablet-0.1.3.txt](https://github.com/mihtjel/nanovna-saver/files/3831761/tablet-0.1.3.txt)

**Comment by mydevpeeps** [comment]
I had just updated this tablet to a newer build, which I guess was on a REALLY OLD version because it updated it to b1511. I am going to update it again and see if that helps. You may have to just declare it doesn't work on older specific builds of windows 10.. I'll let you know.

**Comment by mihtjel** [comment]
Hi,
I'm going to declare something completely different: I think you need to upgrade the firmware on your NanoVNA! :-)

Your firmware is an August 2 2019 build, and builds that old are known to have bugs concerning the transmission of data when read over USB. Even in the working log from your desktop, I see lines like this:
"2019-11-11 08:50:20,180 - NanoVNASaver.SweepWorker - WARNING - Got a non-float data value: 0.270181298 -20278521208 (-20278521208)"

Ie. it saw a value of -20278521208 where it expected a value between -1 and +1

The current revision from edy555 is 0.4.0: https://github.com/ttrftech/NanoVNA/releases
I know some users have good experiences with this firmware titled "NanoVNA-Q" from qrp73: https://github.com/qrp73/NanoVNA-Q/releases

**Comment by mydevpeeps** [comment]
@mihtjel  This is my first time updating a firmware on this device. The stock firmware that comes with it, is, as you mention, the Aug 2 2019 build. I noticed that it has two types, a "4 track" ch version (default) and then a "2 trac" aa version (antenna analyzer). 

Does the edy555 firmware account for what ever the difference is between those two modes? Heck I don't even know what those are! Is there an online resource that describes firmwares better?

**Comment by mihtjel** [comment]
Hi,
the hardware is the same - the only difference between 2-track and 4-track is in the firmware.

I recommend taking a look at the groups.io "nanovna-users" group:

https://groups.io/g/nanovna-users/topics

There is a lot of good resources there, including within the "wiki" on how to upgrade firmware. The kind people there also answer user questions :-)

**Comment by mydevpeeps** [comment]
I updated the firmware and re-ran 0.1.5 on the tablet and this issue went away. Thanks.

**Comment by mydevpeeps** [comment]
:-)

**Comment by mihtjel** [comment]
Excellent! I hope you enjoy using the device and the software!
