### ISSUE TITLE
nanovnasaver v0.1.5  and win10

### ISSUE THREAD

**Issue by ukkohalla** [mihtjel/nanovna-saver#86]
**Describe the bug**

Download in wIn10 o.k.
Error message: "File cannot be opened. Address to deliverer".
Please verify and make a correction. Thanks

**Comment by mihtjel** [comment]
Hi,
the application works fine on Windows 10 - That error message doesn't mean anything to me.

If you have problems running the application, try asking on the nanovna-users groups.io group. To get more details on any error messages, try running the application from a command prompt (cmd.exe).
